# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YVtJ0NtHhVo9ElbiPDictOJf_lmWXCIP
"""

import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as LA

plt.axis([-3,6,-4,8])

plt.xticks(np.arange(-3, 6, 1))
plt.yticks(np.arange(-4, 8, 1))

plt.axis('on')
plt.grid(True)

P = np.array([0,0])
Q = np.array([2,6])
A = np.array([-2,0])
B = np.array([0,-2])


def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

  #Generating all lines
x_PQ = line_gen(P,Q)
x_AB = line_gen(A,B)

#Plotting all lines
plt.plot(x_PQ[0,:],x_PQ[1,:],label='$PQ$')
plt.plot(x_AB[0,:],x_AB[1,:],label='$AB$')


plt.text(0,0,'P(0,0)')
plt.text(2,6,'Q(2,6)')
plt.text(-2,0,'A(-2,0)')
plt.text(0,-2,'B(0,-2)')